
import React from 'react';
import { motion, Variants } from 'framer-motion';
import { 
  DollarSign, 
  Coins, 
  Repeat, 
  ClipboardList, 
  AlertCircle,
  HelpCircle,
  ArrowRight
} from 'lucide-react';
import LegalLayout from './LegalLayout';

const PolicyCard = ({ id, title, icon: Icon, children }: any) => {
  const cardVariants: Variants = {
    hidden: { opacity: 0, y: 20 },
    visible: { opacity: 1, y: 0, transition: { duration: 0.5, ease: "easeOut" } }
  };

  return (
    <motion.section 
      id={id} 
      variants={cardVariants}
      className="bg-[#0a0a0a] border border-white/5 rounded-[40px] p-10 lg:p-12 shadow-2xl relative overflow-hidden group hover:border-blue-500/20 transition-all"
    >
      <div className="absolute top-0 right-0 p-12 opacity-[0.02] group-hover:opacity-[0.05] transition-opacity pointer-events-none">
        <Icon size={200} />
      </div>
      <div className="relative z-10">
        <div className="flex items-center gap-4 mb-10">
           <div className="p-3 bg-blue-600/10 text-blue-500 rounded-2xl group-hover:scale-110 transition-transform">
             <Icon size={24} />
           </div>
           <h2 className="text-3xl font-black text-white tracking-tighter">{title}</h2>
        </div>
        <div className="space-y-6 text-gray-400 font-medium leading-relaxed text-lg">
          {children}
        </div>
      </div>
    </motion.section>
  );
};

const RefundPolicy: React.FC = () => {
  const sections = [
    { id: 'advertiser-refunds', label: '1. Advertiser Refunds' },
    { id: 'bonuses', label: '2. Promotional Credits' },
    { id: 'publisher-earnings', label: '3. Publisher Earnings' },
    { id: 'process', label: '4. The Request Process' },
    { id: 'violations', label: '5. Policy Violations' }
  ];

  return (
    <LegalLayout title="Refund Policy" lastUpdated="October 24, 2024" sections={sections}>
      <PolicyCard id="advertiser-refunds" title="1. Advertiser Refunds" icon={DollarSign}>
        <p>Advertisers may request a refund of their **unspent** account balance under these conditions:</p>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 pt-4">
           <div className="p-6 bg-white/[0.02] border border-white/5 rounded-3xl">
              <h4 className="text-white font-black text-xs uppercase mb-2">Time Limit</h4>
              <p className="text-xs text-gray-500">Refunds only available for funds deposited within the last 6 months.</p>
           </div>
           <div className="p-6 bg-white/[0.02] border border-white/5 rounded-3xl">
              <h4 className="text-white font-black text-xs uppercase mb-2">Processing Fee</h4>
              <p className="text-xs text-gray-500">A standard 5% fee (min. $10) applies to all refund requests.</p>
           </div>
        </div>
        <div className="p-6 bg-red-500/5 border border-red-500/10 rounded-3xl flex gap-4">
           <AlertCircle className="text-red-500 shrink-0" size={20} />
           <p className="text-xs text-red-200">Spent funds are non-refundable as they represent services already rendered (traffic delivered).</p>
        </div>
      </PolicyCard>

      <PolicyCard id="bonuses" title="2. Promotional Credits" icon={Coins}>
        <p>Any funds added to an account as part of a promotion, bonus, or referral program are <span className="text-white">non-refundable</span> and hold no cash value.</p>
      </PolicyCard>

      <PolicyCard id="publisher-earnings" title="3. Publisher Earnings" icon={Repeat}>
        <p>Earnings generated by publishers are subject to strict quality verification.</p>
        <ul className="space-y-4">
           <li className="flex gap-4">
              <div className="w-1.5 h-1.5 rounded-full bg-blue-500 mt-2 shrink-0"></div>
              <p className="text-sm">Earnings deemed to be generated via fraud or bot traffic will be voided.</p>
           </li>
           <li className="flex gap-4">
              <div className="w-1.5 h-1.5 rounded-full bg-blue-500 mt-2 shrink-0"></div>
              <p className="text-sm">Once a payout is processed to a publisher's wallet, it is final.</p>
           </li>
        </ul>
      </PolicyCard>

      <PolicyCard id="process" title="4. Request Process" icon={ClipboardList}>
        <div className="space-y-6">
           <p>To request a refund, follow the protocol below:</p>
           <div className="bg-[#050505] p-10 rounded-[40px] border border-white/5 relative">
              <div className="flex items-center gap-6">
                 <div className="w-12 h-12 bg-blue-600 rounded-2xl flex items-center justify-center text-white font-black">1</div>
                 <div>
                    <h4 className="text-white font-bold">Email Billing</h4>
                    <p className="text-xs text-gray-500">Contact billing@pixelvisionads.com</p>
                 </div>
              </div>
              <div className="w-px h-10 bg-white/10 ml-6 my-2"></div>
              <div className="flex items-center gap-6">
                 <div className="w-12 h-12 bg-blue-600 rounded-2xl flex items-center justify-center text-white font-black">2</div>
                 <div>
                    <h4 className="text-white font-bold">Account Verification</h4>
                    <p className="text-xs text-gray-500">Provide Account ID and reason.</p>
                 </div>
              </div>
              <div className="w-px h-10 bg-white/10 ml-6 my-2"></div>
              <div className="flex items-center gap-6">
                 <div className="w-12 h-12 bg-blue-600 rounded-2xl flex items-center justify-center text-white font-black">3</div>
                 <div>
                    <h4 className="text-white font-bold">Processing</h4>
                    <p className="text-xs text-gray-500">Expect fulfillment within 10 business days.</p>
                 </div>
              </div>
           </div>
        </div>
      </PolicyCard>

      <PolicyCard id="violations" title="5. Policy Violations" icon={AlertCircle}>
        <p className="text-red-400">Accounts terminated due to material breaches of our TOS (e.g., malware, click fraud) are NOT eligible for refunds of any remaining balance.</p>
      </PolicyCard>
    </LegalLayout>
  );
};

export default RefundPolicy;
